name: 'Typecheck'

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '25'
          cache: 'yarn'
      - run: corepack enable
      - run: yarn
      - name: TypeScript type check
        run: yarn run typecheck
